name: blog_frontend
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  test: ^1.0.0
  mockito: ^4.0.0
  build_test: 0.10.4

dependencies:
  blog_common:
    path: ../dart_blog_common
